### ISSUE TITLE
looks great, here are a couple requests to get it to work on our environment 

### ISSUE THREAD

**Issue by reinaldokibel** [shoffman-percona/pmmBackupRestore#2]
Hello Steve, 
I just reviewed the script.   It looks great , wow, lots of comments and validations test, debugging and have a lot of error conditions. Very well written!   However
a)	Our servers do not have access to internet and from the beginning it requires a few downloads, is that really the only way? Can we not download these ahead of time and then move onto next steps? So just check if these files are there already installed?
a.	yum install -y wget
b.	yum install -y pigz
c.	wget [https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/"${vm_version}"/vmutils-linux-amd64-"${vm_version}".tar.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/%22$%7bvm_version%7d%22/vmutils-linux-amd64-%22$%7bvm_version%7d%22.tar.gz)
d.	and others…
b)	# Perform Backup of PMM
a.	Can we backup the smaller dBs ClickHouse, PostgreSQL before we do the larger VM ? 
b.	If we don’t want all the data but the configuration of the PMM and the servers it is monitoring, can we have an option to do so?
c)	We have a NAS mount created on OVA as well as on Container. However the notes say it needs 2x /srv, that is quite a lot, are there any parameters that can be added to the backup command to do a compression or a compressed backup?
a.	### nice to haves ###     #will the backup fit on the filesystem (need >2x the size of the /srv directory)

**Comment by glidepath-labs** [comment]
Since CURL is already installed in all versions of PMM I removed the wget requirement (one less download)
Until this can be included in a future release of PMM (backup script, pigz and vmutils) you will need to download and stage it separately.  

I also added a -s or --storage flag so you can specify where backups/restores will go to/be read from

I went back and forth on backup-sub-sets and ultimately decided that because PMM is more of an appliance, doing a selective backup or restore isn't good for the world so I won't add that here.  

I'm still looking at a way to pre-determine storage needs that isn't overly expensive but all the methods i've found can be system resource intensive so far.
